return {
  -- "ziontee113/syntax-tree-surfer",
  -- "othree/xml.vim",
  -- "vim-scripts/c.vim", -- For C
  -- {
  --   "gennaro-tedesco/nvim-peekup",
  --   event = "VeryLazy",
  --   init = function()
  --     vim.g.peekup_open = "<leader>\""
  --   end
  -- }
  -- {
  --   "Dan7h3x/LazyDo",
  --   branch = "main",
  --   keys = { -- recommended keymap for easy toggle LazyDo in normal and insert modes (arbitrary)
  --     {
  --       "<F5>",
  --       "<ESC><CMD>LazyDoToggle<CR>",
  --       mode = { "n", "i" },
  --     },
  --   },
  --   event = "VeryLazy",
  --   opts = {
  --     -- your config here
  --   },
  -- },
  -- {                          -- Table Mode
  --   'dhruvasagar/vim-table-mode',
  --   ft = {
  --     "markdown",
  --     "org"
  --   },
  --   config = function()
  --     vim.g.table_mode_map_prefix = '|'
  --   end,
  -- },
}
